apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fortune-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fortune-service
    spec:
      containers:
      -  name: fortune-service
         image: nlxarosa/fortune-teller-fortune-service:0.0.3-SNAPSHOT
         ports:
         - containerPort: 8080