apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fortune-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fortune-service
    spec:
      containers:
      -  name: fortune-service
         image: nlxarosa/fortune-teller-fortune-service:0.0.3-SNAPSHOT
         ports:
           - containerPort: 8080
         env:
           - name: SPRING_PROFILES_ACTIVE
             value: mysql
           - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
             value: com.mysql.jdbc.Driver
           - name: spring.jpa.properties.hibernate.dialect
             value: org.hibernate.dialect.MySQL5InnoDBDialect
           - name: SPRING_DATASOURCE_USERNAME
             value: user
           - name: SPRING_DATASOURCE_PASSWORD
             value: password
           - name: SPRING_DATASOURCE_URL
             value: jdbc:mysql://104.155.62.132/fortunes
           - name: eureka.client.serviceUrl.defaultZone
             value: http://104.155.84.100:8761/eureka/
           - name: "eureka.instance.preferIpAddress"
             value: "true"
