---
apiVersion: v1
kind: Service
metadata:
  name: fortune-service-registry
  labels:
    app: fortune-service
spec:
  type: LoadBalancer
  ports:
    - port: 8761
      protocol: TCP
      targetPort: 8761
      nodePort: 31002
  selector:
    app: fortune-service
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fortune-service-registry
  labels:
    app: fortune-service
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fortune-service
        tier: backend
    spec:
      containers:
        - image: nlxarosa/service-registry:0.0.1-SNAPSHOT
          name: fortune-service
          env:
          - name: "eureka.instance.preferIpAddress"
            value: "true"
          ports:
            - containerPort: 8761
              name: db