spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create-drop

ribbon:
  IsSecure: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---

spring:
 profiles: local
 jpa:
   database: H2
   hibernate:
     ddl-auto: create-drop
